version: "3.5"

services:
  ss2:
    image: lockp111/ss2:latest
    container_name: ss2
    environment:
      - PASSWORD=${PASSWORD}
      - PROTO=AES-256-GCM
      - PORT=3000
      - PLUGIN=v2ray-plugin
      - OPTS=server
    ports:
      - "3000:3000"
      - "3000:3000/udp"
    restart: always
    logging:
      options:
        max-size: "1g"