version: "3.5"

services:
  ss2:
    image: lockp111/ss2:latest
    container_name: ss2
    environment:
      - PASSWORD=${PASSWORD}
      - PROTO=AES-256-GCM
      - PORT=3000
      - PLUGIN=v2ray-plugin
      - OPTS=server
    ports:
      - "3000:3000"
      - "3000:3000/udp"
    restart: always
    logging:
      options:
        max-size: "1g"

  s5:
    image: serjs/go-socks5-proxy:latest
    container_name: s5
    environment: 
      - PROXY_USER=s5
      - PROXY_PASSWORD=${PASSWORD}
      - PROXY_PORT=1080
    ports:
      - "1080:1080"
    restart: always
    logging:
      options:
        max-size: "1g"