version: "3.5"

services:
  ss2:
    image: lockp111/ss2:1.2.0
    container_name: ss2
    environment:
      - MODE=-s
      - PASSWORD=${PASSWORD}
      - PROTO=AEAD_CHACHA20_POLY1305
      - PORT=3000
      - PLUGIN=v2ray
      - OPTS=server
      - SERVER_ADDRESS=
      - SOCKS=:1080
    ports:
      # - "1080:1080"
      - "3000:3000"
      - "3000:3000/udp"
    restart: always
    logging:
      options:
        max-size: "1g"
